// <auto-generated />
using System;
using Calisan_Yonetim_Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calisan_Yonetim_Core.Migrations
{
    [DbContext(typeof(CalisanYonetimDbContext))]
    [Migration("20241217213209_added_default_user_data")]
    partial class added_default_user_data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Calisan_Yonetim_Core.Models.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyStatus")
                        .HasColumnType("int");

                    b.HasKey("CompanyId");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            CompanyId = new Guid("758b38d9-e1eb-42bd-b3a3-3418bb7f21e0"),
                            CompanyName = "Pau",
                            CompanyStatus = 1
                        });
                });

            modelBuilder.Entity("Calisan_Yonetim_Core.Models.Personnel", b =>
                {
                    b.Property<Guid>("PersonnelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PersonnelId");

                    b.ToTable("Personnel");

                    b.HasData(
                        new
                        {
                            PersonnelId = new Guid("b14ea420-3499-46a6-9cc8-ded91ca0d0c6"),
                            Email = "admin@pau.net",
                            FistName = "Admin",
                            LastName = "Pau",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Calisan_Yonetim_Core.Models.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("37303b9a-000e-4d5c-b2b7-c3a3bbc1f89d"),
                            RoleName = "Admin",
                            Status = 1
                        },
                        new
                        {
                            RoleId = new Guid("8ed741fe-e8e5-4524-814c-3fa8e9dd8654"),
                            RoleName = "User",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Calisan_Yonetim_Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonnelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PersonnelId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f4e77536-5444-4698-9ebb-e81fcbfe738b"),
                            CompanyId = new Guid("758b38d9-e1eb-42bd-b3a3-3418bb7f21e0"),
                            Password = "admin123",
                            PersonnelId = new Guid("b14ea420-3499-46a6-9cc8-ded91ca0d0c6"),
                            Status = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Calisan_Yonetim_Core.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoleId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleId1");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserRoleId = new Guid("94d1676f-c45b-4557-b018-0e30332250b0"),
                            RoleId = new Guid("37303b9a-000e-4d5c-b2b7-c3a3bbc1f89d"),
                            Status = 0,
                            UserId = new Guid("f4e77536-5444-4698-9ebb-e81fcbfe738b")
                        });
                });

            modelBuilder.Entity("Calisan_Yonetim_Core.Models.User", b =>
                {
                    b.HasOne("Calisan_Yonetim_Core.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Calisan_Yonetim_Core.Models.Personnel", "Personnel")
                        .WithOne("User")
                        .HasForeignKey("Calisan_Yonetim_Core.Models.User", "PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("Calisan_Yonetim_Core.Models.UserRole", b =>
                {
                    b.HasOne("Calisan_Yonetim_Core.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Calisan_Yonetim_Core.Models.Role", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId1");

                    b.HasOne("Calisan_Yonetim_Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Calisan_Yonetim_Core.Models.Company", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Calisan_Yonetim_Core.Models.Personnel", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Calisan_Yonetim_Core.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
